services:
  - type: web
    name: transact-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: Backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - fromGroup: transact-secrets
